// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksdNenx8brOQ3fVnVkdC-OTS_LNsvxIw',
    appId: '1:513433768158:web:31b6f99e7ebd7ebeee724f',
    messagingSenderId: '513433768158',
    projectId: 'instx-72196',
    authDomain: 'instx-72196.firebaseapp.com',
    storageBucket: 'instx-72196.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXFFpKDSvJeYWs6iO2PgYBYkBOCylk0A',
    appId: '1:513433768158:android:fb303cefa56951aaee724f',
    messagingSenderId: '513433768158',
    projectId: 'instx-72196',
    storageBucket: 'instx-72196.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa64LG8P7duQlXF7JIGMX9vz5re1UGlKU',
    appId: '1:513433768158:ios:44f0c10345d14f6bee724f',
    messagingSenderId: '513433768158',
    projectId: 'instx-72196',
    storageBucket: 'instx-72196.appspot.com',
    iosBundleId: 'com.example.instx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa64LG8P7duQlXF7JIGMX9vz5re1UGlKU',
    appId: '1:513433768158:ios:4393fcc9ac6ccbbdee724f',
    messagingSenderId: '513433768158',
    projectId: 'instx-72196',
    storageBucket: 'instx-72196.appspot.com',
    iosBundleId: 'y',
  );
}
